configuration: Release

before_build:
  - cmd: nuget restore

build:
  verbosity: normal
  parallel: true
  publish_nuget: true

deploy:
  provider: NuGet
  api_key:
    secure: 61GnKhv/vndUGtmAu9tITU0MCRhBO+WVL3CDXk5TZLxbDpHkjkCTnyzxp0yrGKTa
  on:
    appveyor_repo_tag: true