configuration: Release

image: Visual Studio 2017

before_build:
  - cmd: nuget restore -Verbosity quiet

build:
  verbosity: minimal
  parallel: true

artifacts:
  path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: 61GnKhv/vndUGtmAu9tITU0MCRhBO+WVL3CDXk5TZLxbDpHkjkCTnyzxp0yrGKTa
  on:
    appveyor_repo_tag: true