configuration: Release

image: Visual Studio 2017

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
          Update-AppveyorBuild -Version "3.3.0-ci.$($env:APPVEYOR_BUILD_NUMBER)+sha.$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

dotnet_csproj:
  patch: true
  file: 'src\Ninject\Ninject.csproj'
  version: '{version}'
  package_version: '{version}'

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%LocalAppData%\NuGet\v3-cache'

before_build:
  - nuget restore -Verbosity quiet
  - choco install opencover.portable --limitoutput
  - choco install codecov --limitoutput

build:
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\src\Ninject.Test\bin\Release\net452\Ninject.Test.dll -noshadow" -filter:"+[Ninject]*" -output:".\Ninject_coverage_net452.xml"
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\src\Ninject.Test\bin\Release\netcoreapp2.0\Ninject.Test.dll -noshadow" -filter:"+[Ninject]*" -output:".\Ninject_coverage_netcoreapp2.0.xml"
  - codecov -f "Ninject_coverage_net452.xml Ninject_coverage_netcoreapp2.0.xml" -v False

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: Sn05A/FiUAlID5v31uaf5EZuYCSo4frLONtrCY+cwY265dU2JUZsl2+sjVeLQyz/
  on:
    appveyor_repo_tag: true